# Generated by Django 4.2.20 on 2026-03-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_email_remove_feedback_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='satisfy',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=30, verbose_name='Are you satisfied with course content?'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sug',
            field=models.TextField(default='', verbose_name='Suggest some changes to the website'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ui',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=30, verbose_name='Did you like the UI of our website?'),
        ),
    ]
