# Generated by Django 4.2.20 on 2026-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_satisfy_alter_feedback_sug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sugg',
            field=models.TextField(default='', verbose_name='Suggest changes in course content or possible additions'),
        ),
    ]
