# Generated by Django 4.2.20 on 2025-03-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_url'),
        ('accounts', '0004_userprofile_bio_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registered_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status_update',
            field=models.TextField(blank=True, help_text='Share your latest update!', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='teacher_students', to='accounts.userprofile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
