# Generated by Django 4.2.20 on 2025-03-09 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_course_url'),
        ('accounts', '0005_userprofile_registered_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registered_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
